[tool.black]
line-length = 120
target-version = ['py310']
exclude = '''
/(
    \.git
  | \.venv
  | venv
  | env
  | __pycache__
  | \.pytest_cache
  | IoT Predictive Maintenance System Analysis and Bug Resolution
  | bug-solution-analysis
)/
'''

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
skip_glob = [
    "*/IoT Predictive Maintenance System Analysis and Bug Resolution/*",
    "*/bug-solution-analysis/*",
    "*/.git/*",
    "*/venv/*",
    "*/env/*",
    "*/__pycache__/*"
]
